### PR TITLE
Correctly desensitize timer callbacks in FLI

### LINKED ISSUE #3229: Performance regression in cocotb 1.7
I had an engineer report a significant performance regression when upgrading from 1.6.2 to 1.7.2. This is the not the first time this complaint has been heard, there was someone on the Gitter who mentioned it as well (it's blocked for me rn so I can't go find it).

### PR DESCRIPTION
**Pull request by ktbarrett**
Small test shows 5x FLI performance. Closes #3229. The whole callback cleanup needs some love, but this is the minimal change to fix the performance regression.

### CODE REVIEW

File: cocotb/share/lib/fli/FliCbHdl.cpp [hunk 1]
```diff
@@ -41,9 +41,11 @@
...
  */
 int FliProcessCbHdl::cleanup_callback() {
-    if (get_call_state() == GPI_PRIMED) {
-        mti_Desensitize(m_proc_hdl);
-        set_call_state(GPI_DELETE);
+    switch (get_call_state()) {
+        case GPI_PRIMED:
+        case GPI_CALL:
+            mti_Desensitize(m_proc_hdl);
+            set_call_state(GPI_DELETE);
```
Comment (ktbarrett) [inline cocotb/share/lib/fli/FliCbHdl.cpp:48]:
```suggestion
            set_call_state(GPI_DELETE);
            break;
        case GPI_DELETE:
        case GPI_FREE:
            break;
```

**Review by marlonjames — APPROVED** [review]
