### PR TITLE
Guess `GPI_LOGIC_ARRAY` as type of parameters with unknown constant types

### LINKED ISSUE #4787: cocotb 2.0.0 VHDL generic access via GHDL
> The way cocotb 1.X handled constants was by using `ConstantObject` which is just a type erased handle object which then expected the user to "just know" the correct way to get the value, producing incorrect results or simulator crashes if used incorrectly.
> 
> 2.0's solution to instead use the more specific types offers a better solution for VHDL users (well those simulators that use the VHPI unlike GHDL...), while providing *a* solution for Verilog users (and GHDL). 
> 
> This is definitely a regression in 2.0, I'd open a new issue with a MRFE. 

 _Originally posted by @ktbarrett in [#2722](https://github.com/cocotb/cocotb/issues/2722#issuecomment-3028262237)_

This issue is about VHDL Generic access not working in current cocotb 2.0.0-dev. In cocotb 1.9.2 it works fine.

Ideally, GHDL would use the VHPI instead of VPI (see https://github.com/ghdl/ghdl/issues/2535) but maybe something can be done about this on the cocotb side to make it work in 2.0.0.

Versions:
- cocotb 2.0.0.dev0+2f707d1d 
- GHDL 6.0.0-dev (5.1.1.r14.g870738a4d)
- Python 3.8

**Minimum Reproducible Failure Example** 

`foo.vhd`
```vhdl
library ieee;
use ieee.std_logic_1164.all;

entity Foo is
  generic (
    G_GENERIC : integer := 3
  );
  port (
    clk     : in std_logic;
    reset_n : in std_logic
  );
end entity;

architecture arch_Foo of Foo is

begin

end architecture;
```

`testbench.py`
```py

import cocotb

@cocotb.test()
async def test_generic_access(dut):
    assert int(dut.G_GENERIC.value) in [3]
```

`test_runner.py`
```py

import os
from cocotb_tools.runner import get_runner

def test_runner():
    sim = os.getenv("SIM", "ghdl")

    runner = get_runner(sim)

    runner.build(
        sources = ["foo.vhd"],
        hdl_toplevel = "foo"
    )

    runner.test(
        test_module = "testbench",
        hdl_toplevel = "foo",
        hdl_toplevel_lang = "vhdl",
    )

if __name__ == "__main__":
    test_runner()
```

Command
```cmd
python test_runner.py
```

Output (cocotb 2.0.0-dev) 👎 
```cmd
loading VPI module '/home/mto/github_cocotb/cocotb/src/cocotb/libs/libcocotbvpi_ghdl.so'
     -.--ns INFO     gpi                                ..mbed/gpi_embed.cpp:93   in _embed_init_python              Using Python 3.8.10 interpreter at /usr/bin/python3.8
     -.--ns INFO     gpi                                ../gpi/GpiCommon.cpp:79   in gpi_print_registered_impl       VPI registered
VPI module loaded!
     0.00ns INFO     cocotb                             Running on GHDL version 6.0.0-dev (5.1.1.r14.g870738a4d) [Dunoon edition]
     0.00ns WARNING  gpi                                vpi_iterate returned NULL for type vpiInstance for object NULL
     0.00ns INFO     cocotb                             Seeding Python random module with 1751620196
     0.00ns INFO     cocotb                             Initialized cocotb v2.0.0.dev0+2f707d1d from /home/mto/github_cocotb/cocotb/src/cocotb
     0.00ns INFO     cocotb                             Running tests
     0.00ns INFO     cocotb.regression                  running testbench.test_generic_access (1/1)
vpi_get: unknown property
     0.00ns WARNING  ..neric_access.test_generic_access Couldn't find a matching object for GPI type GPI_UNKNOWN(0) (path=foo.G_GENERIC)
                                                        Traceback (most recent call last):
                                                          File "/home/mto/MRFE/testbench.py", line 6, in test_generic_access
                                                            assert int(dut.G_GENERIC.value) in [3]
                                                          File "/home/mto/github_cocotb/cocotb/src/cocotb/handle.py", line 469, in __getattr__
                                                            handle = self._get(name)
                                                          File "/home/mto/github_cocotb/cocotb/src/cocotb/handle.py", line 343, in _get
                                                            sub_handle = _make_sim_object(new_handle, self._child_path(key))
                                                          File "/home/mto/github_cocotb/cocotb/src/cocotb/handle.py", line 1717, in _make_sim_object
                                                            raise NotImplementedError(
                                                        NotImplementedError: Couldn't find a matching object for GPI type GPI_UNKNOWN(0) (path=foo.G_GENERIC)
     0.00ns WARNING  cocotb.regression                  testbench.test_generic_access failed
     0.00ns INFO     cocotb.regression                  ***************************************************************************************
                                                        ** TEST                           STATUS  SIM TIME (ns)  REAL TIME (s)  RATIO (ns/s) **
                                                        ***************************************************************************************
                                                        ** testbench.test_generic_access   FAIL           0.00           0.00          0.00  **
                                                        ***************************************************************************************
                                                        ** TESTS=1 PASS=0 FAIL=1 SKIP=0                   0.00           0.00          0.00  **
                                                        ***************************************************************************************
```
Output (cocotb 1.9.2) 👍 
```cmd
test_runner.py:2: UserWarning: Python runners and associated APIs are an experimental feature and subject to change.
  from cocotb.runner import get_runner
INFO: Running command ghdl -i --work=top /home/mto/MRFE/foo.vhd in directory /home/mto/MRFE/sim_build
INFO: Running command ghdl -m --work=top foo in directory /home/mto/MRFE/sim_build
INFO: Running command ghdl -r --work=top foo --vpi=/home/mto/.local/lib/python3.8/site-packages/cocotb/libs/libcocotbvpi_ghdl.so in directory /home/mto/MRFE/sim_build
loading VPI module '/home/mto/.local/lib/python3.8/site-packages/cocotb/libs/libcocotbvpi_ghdl.so'
     -.--ns INFO     gpi                                ..mbed/gpi_embed.cpp:79   in set_program_name_in_venv        Did not detect Python virtual environment. Using system-wide Python interpreter
     -.--ns INFO     gpi                                ../gpi/GpiCommon.cpp:101  in gpi_print_registered_impl       VPI registered
VPI module loaded!
     0.00ns INFO     cocotb                             Running on GHDL version 6.0.0-dev (5.1.1.r14.g870738a4d) [Dunoon edition]
     0.00ns INFO     cocotb                             Running tests with cocotb v1.9.2 from /home/mto/.local/lib/python3.8/site-packages/cocotb
     0.00ns INFO     cocotb                             Seeding Python random module with 1751620416
     0.00ns INFO     cocotb.regression                  Found test testbench.test_generic_access
     0.00ns INFO     cocotb.regression                  running test_generic_access (1/1)
vpi_get: unknown property
     0.00ns INFO     cocotb.regression                  test_generic_access passed
     0.00ns INFO     cocotb.regression                  ***************************************************************************************
                                                        ** TEST                           STATUS  SIM TIME (ns)  REAL TIME (s)  RATIO (ns/s) **
                                                        ***************************************************************************************
                                                        ** testbench.test_generic_access   PASS           0.00           0.00          0.01  **
                                                        ***************************************************************************************
                                                        ** TESTS=1 PASS=1 FAIL=0 SKIP=0                   0.00           0.02          0.00  **
                                                        ***************************************************************************************
```

The only line of code i changed when switching between cocotb 1.9.2 and current 2.0.0-dev is in `testrunner.py`
cocotb 1.9.2 --> `from cocotb.runner import get_runner`
cocotb 2.0.0-dev --> `from cocotb_tools.runner import get_runner`

### PR DESCRIPTION
**Pull request by ktbarrett**
Closes #4787. This is "reasonable" and was effectively what 1.x did. There are still plenty of types where this won't work and may cause failures/crashes, but that's the best we can do considering the VPI doesn't provide type information about parameters.

### CODE REVIEW

File: src/cocotb/share/lib/vpi/VpiImpl.cpp [hunk 1]
```diff
@@ -152,9 +152,11 @@ static gpi_objtype const_type_to_gpi_objtype(int32_t const_type) {
             return GPI_STRING;
         // case vpiTimeConst:  // Not implemented
         default:
-            LOG_DEBUG("Unable to map vpiConst type %d onto GPI type",
-                      const_type);
-            return GPI_UNKNOWN;
+            LOG_WARN(
+                "Unable to map vpiConst type %d onto GPI type,"
```
Comment (cmarqu) [inline src/cocotb/share/lib/vpi/VpiImpl.cpp]:
```suggestion
                "Unable to map vpiConst type %d onto GPI type, "
```
