### PR TITLE
Clean makefiles, fix C/C++ warnings, support Clang

### LINKED ISSUE #1136: Makefile issues, support for building cocotb with Clang
* GCC is called out specifically by the makefiles to build cocotb. There really isn't a good reason for this, Clang is capable of compiling the code.
   * I don't know much about mingw, is it possible we could switch to calling out `cc` and `c++`?
    *  A quick check shows that Clang's `-Wall` includes `-Woverloaded-virtual` so the build fails.
* The name of GCC_ARGS and GXX_ARGS should change.
* The makefiles should respect user supplied CFLAGS and CXXFLAGS. 
* The makefiles don't actually uniformly enable warnings for all platforms, and the number of warnings enabled is rather weak.
* There are still lurking warnings that should be addressed.
 * I have some opinions about `-Werror`, but I'll keep them to myself.

### PR DESCRIPTION
**Pull request by ktbarrett**
Fixes #1136.
* Makefiles use `cc` and `c++` for compilation, so Clang or any other
    compiler can be used to build cocotb.
* Makefiles respect user CFLAGS, CXXFLAGS, LDFLAGS, and LDLIBS
* Increased set of warnings
* Warnings applied for all archs
* Fixed warnings in C/C++ code
* renamed GCC_ARGS and GXX_ARGS to not allude to GCC

### CODE REVIEW

**Comment by cmarqu** [comment]
Does this also fix #1122?

**Comment by ktbarrett** [comment]
It can, I haven't yet seen those warnings with my compilers (GCC 9.2.1 and Clang 8.0.1), but I see why they are thrown and can fix that.

**Comment by ktbarrett** [comment]
I think I will also respect the `CC` and `CXX` user variables, and they will default to `cc` and `c++`.

**Comment by cmarqu** [comment]
This will also help https://github.com/cocotb/cocotb/pull/796#issuecomment-462010801, good.

**Comment by ktbarrett** [comment]
Sorry, don't have python2 on my machine (nor will I).

File: cocotb/share/lib/gpi_log/gpi_logging.c [hunk 1]
```diff
@@ -142,7 +141,7 @@ void gpi_log(const char *name, long level, const char *pathname, const char *fun
         return;
     }
 
-    if (level < local_level)
+    if (level < (long)local_level)
```
Comment (imphil) [inline cocotb/share/lib/gpi_log/gpi_logging.c]: The better type for both `level` and `local_level` is `enum gpi_log_levels`. `local_level` is already of that type, so please change the `level` parameter to be of that type as well. (Most callers of this function come through the `LOG_*` functions in `include/gpi_logging.h` which already uses the enum constants.)

File: cocotb/share/lib/simulator/simulatormodule.c [hunk 2]
```diff
@@ -386,7 +391,16 @@ static PyObject *register_timed_callback(PyObject *self, PyObject *args)
 
     // Extract the time
     PyObject *pTime = PyTuple_GetItem(args, 0);
-    time_ps = PyLong_AsLongLong(pTime);
+    if (PyLong_Check(pTime)) {
+        time_ps = PyLong_AsUnsignedLongLong(pTime);
```
Comment (imphil) [inline cocotb/share/lib/simulator/simulatormodule.c]: The call `PyLong_AsUnsignedLongLong()` needs error handling, according to https://docs.python.org/3/c-api/long.html#c.PyLong_AsUnsignedLongLong.

File: cocotb/share/lib/simulator/simulatormodule.c [hunk 3]
```diff
@@ -386,7 +391,16 @@ static PyObject *register_timed_callback(PyObject *self, PyObject *args)
...
+#if PY_MAJOR_VERSION < 3
+    } else if (PyInt_Check(pTime)) {
+        time_ps = PyInt_AsUnsignedLongLongMask(pTime);
```
Comment (imphil) [inline cocotb/share/lib/simulator/simulatormodule.c]: As above: please add error handling

File: cocotb/share/makefiles/Makefile.inc [hunk 4]
```diff
@@ -72,27 +72,31 @@ export INCLUDES := -I$(COCOTB_SHARE_DIR)/include -I$(PYTHON_INCLUDEDIR)
...
 ifeq ($(ARCH),i686)
-GXX_ARGS    := -m32
+CXX_ARGS    += -m32
 endif
 
 ifeq ($(OS),Darwin)
-GXX_ARGS	+= -g -DDEBUG -fpic
-GCC_ARGS	:= $(GXX_ARGS)
+CXX_ARGS	+= -g -DDEBUG -fpic
+C_ARGS	    += $(CXX_ARGS)
```
Comment (imphil) [inline cocotb/share/makefiles/Makefile.inc]: nit: indent

File: cocotb/share/makefiles/Makefile.inc [hunk 5]
```diff
@@ -72,27 +72,31 @@ export INCLUDES := -I$(COCOTB_SHARE_DIR)/include -I$(PYTHON_INCLUDEDIR)
...
 LIB_EXT		:= dll
 PY_EXT		:= pyd
 else ifeq ($(OS),Linux)
-GXX_ARGS	+= -Werror -Wcast-qual -Wcast-align -Wwrite-strings \
-			-Wall -Wno-unused-parameter \
-			-fno-common -g -DDEBUG -fpic
-GCC_ARGS	= $(GXX_ARGS) -Wstrict-prototypes -Waggregate-return
+CXX_ARGS	+=  -fno-common -g -DDEBUG -fpic
+C_ARGS	    += $(CXX_ARGS)
```
Comment (imphil) [inline cocotb/share/makefiles/Makefile.inc]: For all of this file: please double-check the indentation

File: cocotb/share/makefiles/Makefile.rules [hunk 6]
```diff
@@ -50,14 +50,18 @@ SIM_DEFINE = IUS
 endif
 
 # Add Simulator Define for compilation
-GCC_ARGS+= -D$(SIM_DEFINE)
-GXX_ARGS+= -D$(SIM_DEFINE)
+C_ARGS+= -D$(SIM_DEFINE)
+CXX_ARGS+= -D$(SIM_DEFINE)
```
Comment (imphil) [inline cocotb/share/makefiles/Makefile.rules]: nit: indentation, and please add space before `+=`

File: cocotb/share/lib/simulator/simulatormodule.c (hunk 3 above)
Comment (eric-wieser) [reply cocotb/share/lib/simulator/simulatormodule.c]: Why can't the same code path be used for both of these cases?

File: cocotb/share/makefiles/Makefile.rules (hunk 6 above)
Comment (eric-wieser) [reply cocotb/share/makefiles/Makefile.rules]: meta-nit: this is alignment, not indentation

File: cocotb/share/lib/embed/gpi_embed.c [hunk 7]
```diff
@@ -165,7 +166,7 @@ void embed_init_python(void)
         }
 
         LOG_ERROR("Waiting for %lu seconds - attach to PID %d with your debugger\n", sleep_time, getpid());
-        sleep(sleep_time);
+        sleep((unsigned)sleep_time);
```
[the remark this answers is not in the document]
Comment (ktbarrett) [reply cocotb/share/lib/embed/gpi_embed.c]: This is a narrowing cast on most archs. Clang and GCC complain with -Wconversion on Linux.

**Comment by ktbarrett** [comment]
@imphil I think I've addressed most of your concerns, could you re-review?

File: cocotb/share/include/gpi.h [hunk 8]
```diff
@@ -85,7 +85,7 @@ EXTERN_C_START
 typedef enum gpi_event_e {
     SIM_INFO = 0,
     SIM_TEST_FAIL = 1,
-    SIM_FAIL = 2,
+    SIM_FAIL = 2
 } gpi_event_t;
```
Comment (eric-wieser) [inline cocotb/share/include/gpi.h]: Any reason for this change? Trailing commas are perfectly legal in C99 and C++11. Perhaps we should close out on #1087 decisively first

File: cocotb/share/lib/embed/gpi_embed.c (hunk 7 above)
[the remark this answers is not in the document]
Comment (eric-wieser) [reply cocotb/share/lib/embed/gpi_embed.c]: Agreed with @ktbarrett, this is correct - although I might be tempted to spell it 
```suggestion
        sleep((unsigned int)sleep_time);
```

File: cocotb/share/lib/fli/FliImpl.cpp [hunk 9]
```diff
@@ -751,7 +751,7 @@ GpiIterator::Status FliIterator::next_handle(std::string &name, GpiObjHdl **hdl,
         return GpiIterator::END;
     }
 
-    char *c_name;
+    char *c_name = NULL;
```
Comment (eric-wieser) [inline cocotb/share/lib/fli/FliImpl.cpp]: Would it be clearer to put this in the `default` below instead?

File: cocotb/share/lib/gpi/GpiCommon.cpp [hunk 10]
```diff
@@ -90,7 +90,7 @@ int gpi_print_registered_impl()
     {
         LOG_INFO("%s registered", (*iter)->get_name_c());
     }
-    return registered_impls.size();
+    return (int)registered_impls.size();
```
Comment (eric-wieser) [inline cocotb/share/lib/gpi/GpiCommon.cpp]: Can we instead change the return type to `size_t`?

File: cocotb/share/lib/gpi/GpiCbHdl.cpp [hunk 11]
```diff
@@ -108,12 +108,6 @@ bool GpiHdl::is_this_impl(GpiImplInterface *impl)
     return impl == this->m_impl;
 }
 
-int GpiHdl::initialise(std::string &name)
-{
-    LOG_WARN("Generic initialize, doubt you should have called this");
-    return 0;
-}
-
```
Comment (eric-wieser) [inline cocotb/share/lib/gpi/GpiCbHdl.cpp]: Is this function also removed from the corresponding header?

File: cocotb/share/lib/gpi/gpi_priv.h [hunk 12]
```diff
@@ -65,7 +65,6 @@ class GpiHdl {
     GpiHdl(GpiImplInterface *impl) : m_impl(impl), m_obj_hdl(NULL) { }
     GpiHdl(GpiImplInterface *impl, void *hdl) : m_impl(impl), m_obj_hdl(hdl) { }
     virtual ~GpiHdl() { }
-    virtual int initialise(std::string &name);                   // Post constructor init
```
Comment (eric-wieser) [inline cocotb/share/lib/gpi/gpi_priv.h]: No derived classes define this?

File: cocotb/share/lib/simulator/simulatormodule.c [hunk 13]
```diff
@@ -208,6 +209,7 @@ static PyObject *log_msg(PyObject *self, PyObject *args)
 // Remaining arguments are keyword arguments to be passed to the callback
 static PyObject *register_readonly_callback(PyObject *self, PyObject *args)
 {
+    (void)self;
```
Comment (eric-wieser) [inline cocotb/share/lib/simulator/simulatormodule.c]: I think we might want a cleaner solution to this problem, perhaps
```
#define COCOTB_UNUSED(x) __attribute__((unused)) x
```
which you can then use inside the function signature. Worth looking at how other projects solve this problem cleanly.

File: cocotb/share/lib/simulator/simulatormodule.c [hunk 14]
```diff
@@ -384,9 +389,26 @@ static PyObject *register_timed_callback(PyObject *self, PyObject *args)
...
+    {   // Extract the time
+        PyObject *pTime = PyTuple_GetItem(args, 0);
+        long long pTime_as_longlong = -1;
+        if (PyLong_Check(pTime)) {
+            // overflow case returns -1
+            pTime_as_longlong = PyLong_AsLongLong(pTime);
+#if PY_MAJOR_VERSION < 3
+        } else if (PyInt_Check(pTime)) {
+            pTime_as_longlong = (long long)PyInt_AsLong(pTime);
+#endif
```
Comment (eric-wieser) [inline cocotb/share/lib/simulator/simulatormodule.c]: Why can't you use `PyLong_AsLongLong` unconditionally here?

File: cocotb/share/lib/simulator/simulatormodule.c [hunk 15]
```diff
@@ -384,9 +389,26 @@ static PyObject *register_timed_callback(PyObject *self, PyObject *args)
...
+        }
+        /* check negative covers negative values parsed the above functions, the overflow case with
+           PyLong_AsLongLong, and the case where the given value is neither a Long or an Int */
+        if (pTime_as_longlong < 0) {
+            PyErr_SetString(PyExc_TypeError, "Time value must be a positive integer!\n");
+            return NULL;
```
Comment (eric-wieser) [inline cocotb/share/lib/simulator/simulatormodule.c]: I would add:
```
if (pTime_as_longlong == -1 && PyError_Occured()) {
    return NULL;
}
else if (pTime_as_longlong < 0) {
    PyErr_SetString(PyExc_ValueError, "Time value must be a positive integer!\n");
}
```

File: cocotb/share/lib/simulator/simulatormodule.c [hunk 16]
```diff
@@ -776,14 +815,15 @@ static PyObject *get_type(PyObject *self, PyObject *args)
         return NULL;
     }
 
-    result = gpi_get_object_type((gpi_sim_hdl)hdl);
+    result = (int)gpi_get_object_type((gpi_sim_hdl)hdl);
```
Comment (eric-wieser) [inline cocotb/share/lib/simulator/simulatormodule.c]: I think this would be clearer if you declared `result` to be the correct type, and added the cast on the line below.

File: cocotb/share/lib/vpi/VpiCbHdl.cpp [hunk 17]
```diff
@@ -327,7 +327,7 @@ int VpiSignalObjHdl::set_signal_value(long value)
 {
     s_vpi_value value_s;
 
-    value_s.value.integer = value;
+    value_s.value.integer = (int)value;
```
Comment (eric-wieser) [inline cocotb/share/lib/vpi/VpiCbHdl.cpp]: This looks like a bug to me - although one that was already here. Worth at least calling out with a TODO and a github issue, if you don't want to think about fixing it now.

File: cocotb/share/makefiles/Makefile.inc [hunk 18]
```diff
@@ -69,41 +69,45 @@ export LIB_DIR=$(BUILD_DIR)/libs/$(ARCH)
...
-GXX_ARGS    := -m32
+CXX_ARGS   += -m32
 endif
 
 ifeq ($(OS),Darwin)
-GXX_ARGS	+= -g -DDEBUG -fpic
-GCC_ARGS	:= $(GXX_ARGS)
+CXX_ARGS   := -g -DDEBUG -fpic
+C_ARGS     := $(CXX_ARGS)
 else ifeq ($(OS),Msys)
```
Comment (eric-wieser) [inline cocotb/share/makefiles/Makefile.inc]: confused why you use `+=` above then overwrite with `:=` here

File: cocotb/triggers.py [hunk 19]
```diff
@@ -173,7 +173,7 @@ def __init__(self, time_ps, units=None):
     def prime(self, callback):
         """Register for a timed callback"""
         if self.cbhdl == 0:
-            self.cbhdl = simulator.register_timed_callback(self.sim_steps,
+            self.cbhdl = simulator.register_timed_callback(int(self.sim_steps),
```
Comment (eric-wieser) [inline cocotb/triggers.py]: Why is this necessary?

File: cocotb/share/lib/vpi/VpiCbHdl.cpp (hunk 17 above)
Comment (imphil) [reply cocotb/share/lib/vpi/VpiCbHdl.cpp]: The correct solution would be making set_signal_value take an int instead of a long. I've opened https://github.com/cocotb/cocotb/issues/1202 to take care of that.

File: cocotb/share/lib/fli/FliImpl.cpp (hunk 9 above)
Comment (ktbarrett) [reply cocotb/share/lib/fli/FliImpl.cpp]: Uninitialized variables are code smells IMO. The code base is littered with them, but that's a problem for another day.

File: cocotb/share/lib/simulator/simulatormodule.c (hunk 13 above)
Comment (ktbarrett) [reply cocotb/share/lib/simulator/simulatormodule.c]: If all the sources were C++ you could just leave off the parameter name. But since they are not, we could use the void cast or the unused attribute. But there [doesn't seem to be any difference](https://godbolt.org/z/y8TauJ), and the attribute yields longer function specs that have to be duplicated at declaration and definition, and is an extension.

File: cocotb/share/lib/fli/FliImpl.cpp (hunk 9 above)
Comment (eric-wieser) [reply cocotb/share/lib/fli/FliImpl.cpp]: They're a feature once checked by a compiler - if we were to add a case to the switch below that forgets to set c_name, then either:
* This line exists, the compiler does not find our mistake
* This line does not exist, the compiler warns that c_name is used initialized

The second case seems like an obvious win to me.

File: cocotb/share/lib/gpi/GpiCommon.cpp (hunk 10 above)
Comment (eric-wieser) [reply cocotb/share/lib/gpi/GpiCommon.cpp]: CI fails because you changed the return type but forgot to remove this cast.

File: cocotb/share/lib/simulator/simulatormodule.c (hunk 13 above)
Comment (eric-wieser) [reply cocotb/share/lib/simulator/simulatormodule.c]: There's obviously no difference in compiler output, my argument stems from readability. To a newcomer, `UNUSED` is easier to understand than `(void)`, especially if you out an explanatory comment above the macro definition.

> function specs that have to be duplicated at declaration and definition

Are you sure this is true?

> and is an extension.

Hence the suggestion to wrap it in a macro. Searching online finds many much better macros, the one I suggested was just an example.

File: cocotb/share/lib/simulator/simulatormodule.c [hunk 20]
```diff
@@ -394,9 +399,15 @@ static PyObject *register_timed_callback(PyObject *self, PyObject *args)
         return NULL;
     }
 
-    // Extract the time
-    PyObject *pTime = PyTuple_GetItem(args, 0);
-    time_ps = PyLong_AsLongLong(pTime);
+    {   // Extract the time
+        PyObject *pTime = PyTuple_GetItem(args, 0);
+        long long pTime_as_longlong = PyLong_AsLongLong(pTime);
+        if (pTime_as_longlong < 0) {
```
Comment (eric-wieser) [inline cocotb/share/lib/simulator/simulatormodule.c]: Please use the logic from https://github.com/cocotb/cocotb/pull/1137#discussion_r348406932, this doesn't handle errors correctly.

File: cocotb/share/include/gpi.h (hunk 8 above)
Comment (ktbarrett) [reply cocotb/share/include/gpi.h]: the commit was removed

**Comment by ktbarrett** [comment]
@imphil Could you have another look at this?
