### PR TITLE
set_signal_value_long() bugfixes and improvements

### LINKED ISSUE #268: 32-bit signals are driven by binary string and not the integer value
In handle.py, the function setimmediatevalue() will check if the value is an integer and then check if the integer is less than 0x7fffffff and then it will drive the simulator quicker if it is.  It seems like any 32-bit value should be able to be driven in the same manner.  I realize that that if the value uses the most significant bit, then the C-function, will treat that value as a negative integer, but from the code I have looked at, there wouldn't be any impact to the way the signal is driven.

@chiggs Is there a reason that any 32-bit and below values don't use the faster interface, instead of 31-bit and below?  It seems like the C-Interface would support this.

### LINKED ISSUE #913: Assigning Python ints to signals >32 bits
If I assign a signed value to a signal larger than 32 bits wide, cocotb attempts to convert the int into an unsigned little-endian BinaryValue before assigning the value ([code](https://github.com/potentialventures/cocotb/blob/master/cocotb/handle.py#L592)). When it receives my negative value, the `_convert_to_unsigned` method fails and gives me a totally useless stacktrace. I know to look for this now, but wasted my time until I figured this out; and lucky for me I could, others may not be so lucky.

This convenience conversion makes a poor assumption rather than informing the user it doesn't have enough information to continue. This is bad coding practice. Instead, it might be better to give a warning or throw an error stating that you cannot assign Python ints to signals greater than 32 bit wide, but instead it will only take a BinaryValue for such signals.

```python
width = len(dut.data)   # dut.data begin a 36 bit width sfixed
for i in range(n):
    yield RisingEdge(dut.clk)
    dut.data <= randint(-(2**(width-1)), (2**(width-1))-1)
```

### LINKED ISSUE #1202: IntegerObject: Document and ensure its 32 bit
`IntegerObject` is used to set int/integer nets as defined in SystemVerilog, which are 32 bit (signed) values. See https://github.com/cocotb/cocotb/issues/268 for a discussion on signed-ness.

- `IntegerObject` doesn't check the size, which could lead to loss of data.
- We need to document that `IntegerObject` is 32 bit.
- Our backend functionality, starting with `simulator.set_signal_val_long`, uses long instead of int as data type and in the function names. That should be cleaned up to say int.

### PR DESCRIPTION
**Pull request by elgorwi**
Some bugfixes and improvements for setting signals using python ints: 
closes #1202 
closes #913 
closes #268 

This PR is essentially a merge of PR #1792 , PR #1742  and #1744 .
For more details refer to the linked issues and PRs.

### CODE REVIEW

**Comment by elgorwi** [comment]
Not sure why CI (private) (Linux-RivieraPRO-Verilog) is failing. CI (private) (Linux-RivieraPRO-VHDL) is passing.

**Comment by themperek** [comment]
> Not sure why CI (private) (Linux-RivieraPRO-Verilog) is failing. CI (private) (Linux-RivieraPRO-VHDL) is passing.

```
2021-01-02T09:04:27.5982795Z # COUT: 529553.46ns INFO     cocotb.regression                         regression.py:466  in _start_test                     Running test 116/123: test_integer
2021-01-02T09:04:27.5986091Z # COUT: 529553.46ns INFO     ...test.test_integer.0x7f7af4d39dd8       decorators.py:313  in _advance                        Starting test: "test_integer"
2021-01-02T09:04:27.5989041Z # COUT:                                                                                                                      Description: Test access to integers.
2021-01-02T09:04:27.6150056Z # COUT: 529583.46ns ERROR    cocotb.regression                         regression.py:399  in _score_test                     Test Failed: test_integer (result was AssertionError)
2021-01-02T09:04:27.6153855Z # COUT:                                                                                                                      Traceback (most recent call last):
2021-01-02T09:04:27.6157093Z # COUT:                                                                                                                        File "/home/az_devops_agent/agent/_work/1/s/tests/test_cases/test_cocotb/test_handle.py", line 216, in test_integer
2021-01-02T09:04:27.6159542Z # COUT:                                                                                                                          assert int(dut.stream_in_int) == value
2021-01-02T09:04:27.6161988Z # COUT:                                                                                                                      AssertionError
2021-01-02T09:04:27.6164589Z # COUT: 529583.46ns INFO     cocotb.regression                         regression.py:466  in _start_test                     Running test 117/123: test_integer_overflow
2021-01-02T09:04:27.6167271Z # COUT: 529583.46ns INFO     ..t_integer_overflow.0x7f7af4d395c0       decorators.py:313  in _advance                        Starting test: "test_integer_overflow"
2021-01-02T09:04:27.6169987Z # COUT:                                                                                                                      Description: Test integer overflow.
2021-01-02T09:04:27.6265180Z # COUT: 529593.46ns ERROR    cocotb.regression                         regression.py:373  in _score_test                     Test passed but we expected an error: test_integer_overflow (result was TestSuccess)
2021-01-02T09:04:27.6271931Z # COUT: 529593.46ns INFO     cocotb.regression                         regression.py:466  in _start_test                     Running test 118/123: test_integer_underflow
2021-01-02T09:04:27.6274966Z # COUT: 529593.46ns INFO     .._integer_underflow.0x7f7af4d39588       decorators.py:313  in _advance                        Starting test: "test_integer_underflow"
2021-01-02T09:04:27.6280594Z # COUT:                                                                                                                      Description: Test integer underflow.
2021-01-02T09:04:27.6283113Z # COUT: 529593.46ns ERROR    ..coroutine.Task 326.0x7f7af4d256d8        scheduler.py:506  in unschedule                      Exception raised by this forked coroutine
2021-01-02T09:04:27.6376752Z # COUT: 529593.46ns INFO     cocotb.regression                         regression.py:393  in _score_test                     Test errored as expected: test_integer_underflow (result was OverflowError)
2021-01-02T09:04:27.6380484Z # COUT: 529593.46ns INFO     cocotb.regression                         regression.py:466  in _start_test                     Running test 119/123: test_real_assign_double
2021-01-02T09:04:27.6382995Z # COUT: 529593.46ns INFO     ..real_assign_double.0x7f7af4d39c18       decorators.py:313  in _advance                        Starting test: "test_real_assign_double"
2021-01-02T09:04:27.6385545Z # COUT:                                                                                                                      Description: 
2021-01-02T09:04:27.6387759Z # COUT:                                                                                                                          Assign a random floating point value, read it back from the DUT and check
2021-01-02T09:04:27.6390436Z # COUT:                                                                                                                          it matches what we assigned
2021-01-02T09:04:27.6392408Z # COUT:                        

2021-01-02T09:05:32.4657632Z # COUT:     20.01ns INFO     cocotb.regression                         regression.py:466  in _start_test                     Running test 11/19: test_in_vect_packed_packed_unpacked
2021-01-02T09:05:32.4659988Z # COUT:     20.01ns INFO     ..ed_packed_unpacked.0x7f832e594208       decorators.py:313  in _advance                        Starting test: "test_in_vect_packed_packed_unpacked"
2021-01-02T09:05:32.4662891Z # COUT:                                                                                                                      Description: None
2021-01-02T09:05:32.4706373Z # COUT: Setting: dut.in_vect_packed_packed_unpacked type <class 'cocotb.handle.NonHierarchyIndexableObject'>
2021-01-02T09:05:32.4718504Z # COUT:     21.01ns ERROR    ...coroutine.Task 21.0x7f832e567470        scheduler.py:506  in unschedule                      Exception raised by this forked coroutine
2021-01-02T09:05:32.4802826Z # COUT:     21.01ns ERROR    cocotb.regression                         regression.py:399  in _score_test                     Test Failed: test_in_vect_packed_packed_unpacked (result was OverflowError)
2021-01-02T09:05:32.4806248Z # COUT:                                                                                                                      Traceback (most recent call last):
2021-01-02T09:05:32.4808918Z # COUT:                                                                                                                        File "/home/az_devops_agent/agent/_work/1/s/cocotb/scheduler.py", line 265, in _do_writes
2021-01-02T09:05:32.4811138Z # COUT:                                                                                                                          func(*args)
2021-01-02T09:05:32.4815776Z # COUT:                                                                                                                      OverflowError: Value (95869805) out of range for assignment of 9-bit signal (in_vect_packed_packed_unpacked[0])
                                                                                                  
```

File: cocotb/share/lib/simulator/simulatormodule.cpp [hunk 1]
```diff
@@ -661,16 +668,44 @@ static PyObject *set_signal_val_real(gpi_hdl_Object<gpi_sim_hdl> *self, PyObject
...
     gpi_set_action_t action;
+    limits_e limits;
 
-    if (!PyArg_ParseTuple(args, "il:set_signal_val_long", &action, &value)) {
+    if (!PyArg_ParseTuple(args, "iLi:set_signal_val_int", &action, &value, &limits)) {
         return NULL;
     }
 
-    gpi_set_signal_value_long(self->hdl, value, action);
+    if (limits == limits_e::SIGNED_32BIT) {
```
Comment (eric-wieser) [inline cocotb/share/lib/simulator/simulatormodule.cpp:681]: What's the motivation for handling this casting in C instead of Python?

File: tests/test_cases/test_cocotb/test_handle.py [hunk 2]
```diff
@@ -66,21 +66,172 @@ async def test_delayed_assignment_still_errors(dut):
...
+    assert int(dut.stream_in_int) == value
+
+
+@cocotb.test(expect_error=AttributeError if cocotb.SIM_NAME in ["Icarus Verilog"] else OverflowError)
+async def test_integer_underflow(dut):
+    """Test integer underflow."""
+    value = -2**32-1
+    dut.stream_in_int = value
+    await cocotb.triggers.Timer(10, 'ns')
+    assert int(dut.stream_in_int) == value
```
Comment (eric-wieser) [inline tests/test_cases/test_cocotb/test_handle.py:234]: `OverflowError` should be caught in the test, as:
```suggestion
@cocotb.test(expect_error=AttributeError if cocotb.SIM_NAME in ["Icarus Verilog"] else ())
async def test_integer_underflow(dut):
    """Test integer underflow."""
    value = -2**32-1
    with assert_raises(OverflowError):
        dut.stream_in_int = value
```

Same comment applies to all these tests.

File: cocotb/handle.py [hunk 3]
```diff
@@ -855,7 +880,7 @@ def _set_value(self, value, call_sim):
                 "Unsupported type for integer value assignment: {} ({!r})"
                 .format(type(value), value))
```
Comment (eric-wieser) [inline cocotb/handle.py:882]: The validation needs to happen here before `call_sim` is called, otherwise the user won't get an error immediately.

**Review by ktbarrett — COMMENTED** [review]
I thought be had agreed that we should be using `int64_t`? We are currently using an old spec of the VHPI. The most recent version has corrected the `vhpiIntT` to be a 64 bit signed integer. You can probably leave it named `set_signal_value_long` and just update the parameter type.

File: cocotb/handle.py [hunk 4]
```diff
@@ -706,17 +715,30 @@ def _set_value(self, value, call_sim):
         """
         value, set_action = self._check_for_set_action(value)
 
-        if isinstance(value, int) and value < 0x7fffffff and len(self) <= 32:
-            call_sim(self, self._handle.set_signal_val_long, set_action, value)
-            return
+        if isinstance(value, int):
+            if len(self) <= 32:
+                call_sim(self, self._handle.set_signal_val_int, set_action, value, int(_Limits.VECTOR_NBIT))
```
Comment (ktbarrett) [inline cocotb/handle.py:720]: This needs to be moved below below the check for overflow. Doing this in C is too late. The traceback will not lead to the site of the bad call.

**Comment by ktbarrett** [comment]
Raising `OverflowError` instead of truncating is a change in behavior, but I don't much care. I'd like to see this change in 1.5. Sorry @elgorwi about dropping the ball on the other PRs.

File: cocotb/share/lib/simulator/simulatormodule.cpp (hunk 1 above)
Comment (elgorwi) [reply cocotb/share/lib/simulator/simulatormodule.cpp:681]: Your initial recommendation was to do the range checking in C++ for performance reasons. For this we need a type large enough to represent both int32_t and uint32_t, so using int64_t for the comparisons seemed the right solution.
After the range checking the value is cast down to 32 bit. Am I missing something here?

File: tests/test_cases/test_cocotb/test_handle.py (hunk 2 above)
Comment (elgorwi) [reply tests/test_cases/test_cocotb/test_handle.py:234]: OK I see, I'll fix this up

File: cocotb/handle.py (hunk 3 above)
Comment (elgorwi) [reply cocotb/handle.py:882]: > The validation needs to happen here before `call_sim` is called, otherwise the user won't get an error immediately.

Are you suggesting that doing the range checks in C++ as you recommended earlier is not desired after all?

Comment (eric-wieser) [reply cocotb/handle.py:882]: Would you mind linking to where I said that? Apologies in advance if my opinions are inconsistent over time!

Comment (elgorwi) [reply cocotb/handle.py:882]: Fully understand that opinions can change over time. Here's some links:
https://github.com/cocotb/cocotb/pull/1742#discussion_r419086506
https://github.com/cocotb/cocotb/pull/1742#discussion_r419086122

**Comment by elgorwi** [comment]
> I thought be had agreed that we should be using `int64_t`? We are currently using an old spec of the VHPI. The most recent version has corrected the `vhpiIntT` to be a 64 bit signed integer. You can probably leave it named `set_signal_value_long` and just update the parameter type.

That's not what I recall:
https://github.com/cocotb/cocotb/pull/1742#issuecomment-623092622

**Comment by elgorwi** [comment]
> 
> 
> > Not sure why CI (private) (Linux-RivieraPRO-Verilog) is failing. CI (private) (Linux-RivieraPRO-VHDL) is passing.
> 
> ```
> 2021-01-02T09:04:27.5982795Z # COUT: 529553.46ns INFO     cocotb.regression                         regression.py:466  in _start_test                     Running test 116/123: test_integer
> 2021-01-02T09:04:27.5986091Z # COUT: 529553.46ns INFO     ...test.test_integer.0x7f7af4d39dd8       decorators.py:313  in _advance                        Starting test: "test_integer"
> 2021-01-02T09:04:27.5989041Z # COUT:                                                                                                                      Description: Test access to integers.
> 2021-01-02T09:04:27.6150056Z # COUT: 529583.46ns ERROR    cocotb.regression                         regression.py:399  in _score_test                     Test Failed: test_integer (result was AssertionError)
> 2021-01-02T09:04:27.6153855Z # COUT:                                                                                                                      Traceback (most recent call last):
> 2021-01-02T09:04:27.6157093Z # COUT:                                                                                                                        File "/home/az_devops_agent/agent/_work/1/s/tests/test_cases/test_cocotb/test_handle.py", line 216, in test_integer
> 2021-01-02T09:04:27.6159542Z # COUT:                                                                                                                          assert int(dut.stream_in_int) == value
> 2021-01-02T09:04:27.6161988Z # COUT:                                                                                                                      AssertionError
> 2021-01-02T09:04:27.6164589Z # COUT: 529583.46ns INFO     cocotb.regression                         regression.py:466  in _start_test                     Running test 117/123: test_integer_overflow
> 2021-01-02T09:04:27.6167271Z # COUT: 529583.46ns INFO     ..t_integer_overflow.0x7f7af4d395c0       decorators.py:313  in _advance                        Starting test: "test_integer_overflow"
> 2021-01-02T09:04:27.6169987Z # COUT:                                                                                                                      Description: Test integer overflow.
> 2021-01-02T09:04:27.6265180Z # COUT: 529593.46ns ERROR    cocotb.regression                         regression.py:373  in _score_test                     Test passed but we expected an error: test_integer_overflow (result was TestSuccess)
> 2021-01-02T09:04:27.6271931Z # COUT: 529593.46ns INFO     cocotb.regression                         regression.py:466  in _start_test                     Running test 118/123: test_integer_underflow
> 2021-01-02T09:04:27.6274966Z # COUT: 529593.46ns INFO     .._integer_underflow.0x7f7af4d39588       decorators.py:313  in _advance                        Starting test: "test_integer_underflow"
> 2021-01-02T09:04:27.6280594Z # COUT:                                                                                                                      Description: Test integer underflow.
> 2021-01-02T09:04:27.6283113Z # COUT: 529593.46ns ERROR    ..coroutine.Task 326.0x7f7af4d256d8        scheduler.py:506  in unschedule                      Exception raised by this forked coroutine
> 2021-01-02T09:04:27.6376752Z # COUT: 529593.46ns INFO     cocotb.regression                         regression.py:393  in _score_test                     Test errored as expected: test_integer_underflow (result was OverflowError)
> 2021-01-02T09:04:27.6380484Z # COUT: 529593.46ns INFO     cocotb.regression                         regression.py:466  in _start_test                     Running test 119/123: test_real_assign_double
> 2021-01-02T09:04:27.6382995Z # COUT: 529593.46ns INFO     ..real_assign_double.0x7f7af4d39c18       decorators.py:313  in _advance                        Starting test: "test_real_assign_double"
> 2021-01-02T09:04:27.6385545Z # COUT:                                                                                                                      Description: 
> 2021-01-02T09:04:27.6387759Z # COUT:                                                                                                                          Assign a random floating point value, read it back from the DUT and check
> 2021-01-02T09:04:27.6390436Z # COUT:                                                                                                                          it matches what we assigned
> 2021-01-02T09:04:27.6392408Z # COUT:                        
> 
> 2021-01-02T09:05:32.4657632Z # COUT:     20.01ns INFO     cocotb.regression                         regression.py:466  in _start_test                     Running test 11/19: test_in_vect_packed_packed_unpacked
> 2021-01-02T09:05:32.4659988Z # COUT:     20.01ns INFO     ..ed_packed_unpacked.0x7f832e594208       decorators.py:313  in _advance                        Starting test: "test_in_vect_packed_packed_unpacked"
> 2021-01-02T09:05:32.4662891Z # COUT:                                                                                                                      Description: None
> 2021-01-02T09:05:32.4706373Z # COUT: Setting: dut.in_vect_packed_packed_unpacked type <class 'cocotb.handle.NonHierarchyIndexableObject'>
> 2021-01-02T09:05:32.4718504Z # COUT:     21.01ns ERROR    ...coroutine.Task 21.0x7f832e567470        scheduler.py:506  in unschedule                      Exception raised by this forked coroutine
> 2021-01-02T09:05:32.4802826Z # COUT:     21.01ns ERROR    cocotb.regression                         regression.py:399  in _score_test                     Test Failed: test_in_vect_packed_packed_unpacked (result was OverflowError)
> 2021-01-02T09:05:32.4806248Z # COUT:                                                                                                                      Traceback (most recent call last):
> 2021-01-02T09:05:32.4808918Z # COUT:                                                                                                                        File "/home/az_devops_agent/agent/_work/1/s/cocotb/scheduler.py", line 265, in _do_writes
> 2021-01-02T09:05:32.4811138Z # COUT:                                                                                                                          func(*args)
> 2021-01-02T09:05:32.4815776Z # COUT:                                                                                                                      OverflowError: Value (95869805) out of range for assignment of 9-bit signal (in_vect_packed_packed_unpacked[0])
>                                                                                                   
> ```

Thanks @themperek , could you post the log from the last run please?

**Comment by themperek** [comment]
> Thanks @themperek , could you post the log from the last run please?

```
2021-01-04T09:18:16.4492865Z # COUT: 529553.46ns INFO     cocotb.regression                         regression.py:466  in _start_test                     Running test 116/123: test_integer
2021-01-04T09:18:16.4495948Z # COUT: 529553.46ns INFO     ...test.test_integer.0x7f8b0f0a1ef0       decorators.py:313  in _advance                        Starting test: "test_integer"
2021-01-04T09:18:16.4498520Z # COUT:                                                                                                                      Description: Test access to integers.
2021-01-04T09:18:16.4632094Z # COUT: 529573.46ns ERROR    cocotb.regression                         regression.py:399  in _score_test                     Test Failed: test_integer (result was AssertionError)
2021-01-04T09:18:16.4635960Z # COUT:                                                                                                                      Traceback (most recent call last):
2021-01-04T09:18:16.4638537Z # COUT:                                                                                                                        File "/home/az_devops_agent/agent/_work/1/s/tests/test_cases/test_cocotb/test_handle.py", line 242, in test_integer
2021-01-04T09:18:16.4641378Z # COUT:                                                                                                                          await int_values_test(dut.stream_in_int, values, limits=_Limits.SIGNED_NBIT)
2021-01-04T09:18:16.4644472Z # COUT:                                                                                                                        File "/home/az_devops_agent/agent/_work/1/s/tests/test_cases/test_cocotb/test_handle.py", line 85, in int_values_test
2021-01-04T09:18:16.4647417Z # COUT:                                                                                                                          assert got == val, "Expected value {}, got value {}!".format(val, got)
2021-01-04T09:18:16.4651006Z # COUT:                                                                                                                      AssertionError: Expected value -1, got value 4294967295!
2021-01-04T09:18:16.4654385Z # COUT: 529573.46ns INFO     cocotb.regression                         regression.py:466  in _start_test                     Running test 117/123: test_integer_overflow
2021-01-04T09:18:16.4657471Z # COUT: 529573.46ns INFO     ..t_integer_overflow.0x7f8b0f0a1eb8       decorators.py:313  in _advance                        Starting test: "test_integer_overflow"
2021-01-04T09:18:16.4659818Z # COUT:                                                                                                                      Description: Test integer overflow.
2021-01-04T09:18:16.4725800Z # COUT: 529573.46ns ERROR    cocotb.regression                         regression.py:399  in _score_test                     Test Failed: test_integer_overflow (result was AssertionError)
2021-01-04T09:18:16.4728822Z # COUT:                                                                                                                      Traceback (most recent call last):
2021-01-04T09:18:16.4731824Z # COUT:                                                                                                                        File "/home/az_devops_agent/agent/_work/1/s/tests/test_cases/test_cocotb/test_handle.py", line 249, in test_integer_overflow
2021-01-04T09:18:16.4734942Z # COUT:                                                                                                                          await int_overflow_test(dut.stream_in_int, value)
2021-01-04T09:18:16.4737805Z # COUT:                                                                                                                        File "/home/az_devops_agent/agent/_work/1/s/tests/test_cases/test_cocotb/test_handle.py", line 106, in int_overflow_test
2021-01-04T09:18:16.4740131Z # COUT:                                                                                                                          signal <= value
2021-01-04T09:18:16.4742618Z # COUT:                                                                                                                        File "/usr/lib/python3.6/contextlib.py", line 88, in __exit__
2021-01-04T09:18:16.4745224Z # COUT:                                                                                                                          next(self.gen)
2021-01-04T09:18:16.4747535Z # COUT:                                                                                                                        File "/home/az_devops_agent/agent/_work/1/s/tests/test_cases/test_cocotb/common.py", line 50, in assert_raises
2021-01-04T09:18:16.4750237Z # COUT:                                                                                                                          assert False, "{} was not raised".format(exc_type.__name__)
2021-01-04T09:18:16.4752962Z # COUT:                                                                                                                      AssertionError: OverflowError was not raised

```

File: documentation/source/newsfragments/913.bugfix.rst [hunk 5]
```diff
@@ -0,0 +1 @@
+Assigning Python ints to signals greater than 32-bit wide will now work correctly for negative values.
```
Comment (ktbarrett) [inline documentation/source/newsfragments/913.bugfix.rst:1]: Could you also add a second newsfragment of the type 'change' to list the change of behavior when assigning ints that are out of range of the signal? They used to truncate and warn, but now they throw.

File: tests/test_cases/test_cocotb/test_handle.py [hunk 6]
```diff
@@ -66,21 +67,193 @@ async def test_delayed_assignment_still_errors(dut):
...
+        signal <= val
+        await Timer(10, 'ns')
+
+        if limits == _Limits.VECTOR_NBIT:
+            if val < 0:
+                got = signal.value.signed_integer
+            else:
+                got = signal.value.integer
+        else:
+            got = int(signal)
```
Comment (ktbarrett) [inline tests/test_cases/test_cocotb/test_handle.py:83]: `.value` on integer and enum handles should return an `int`.
```suggestion
            got = signal.value
```

File: tests/test_cases/test_multi_dimension_array/test_cocotb_array.py [hunk 7]
```diff
@@ -117,7 +117,7 @@ async def test_in_vect_packed_packed_packed(dut):
 async def test_in_vect_packed_packed_unpacked(dut):
     await Timer(1, "ns")
     print("Setting: dut.in_vect_packed_packed_unpacked type %s" % type(dut.in_vect_packed_packed_unpacked))
-    dut.in_vect_packed_packed_unpacked = [95869805, 95869805, 95869805]
+    dut.in_vect_packed_packed_unpacked = [365, 365, 365]
```
Comment (ktbarrett) [inline tests/test_cases/test_multi_dimension_array/test_cocotb_array.py:120]: What's this change?

File: tests/test_cases/test_cocotb/test_handle.py [hunk 8]
```diff
@@ -66,21 +67,193 @@ async def test_delayed_assignment_still_errors(dut):
...
+    """Test 128-bit vector overflow."""
+    value = gen_int_ovfl_value(len(dut.stream_in_data_dqword))
+    await int_overflow_test(dut.stream_in_data_dqword, value)
+
+
+@cocotb.test()
+async def test_int_128bit_underflow(dut):
+    """Test 128-bit vector underflow."""
+    value = gen_int_unfl_value(len(dut.stream_in_data_dqword))
+    await int_overflow_test(dut.stream_in_data_dqword, value)
```
Comment (ktbarrett) [inline tests/test_cases/test_cocotb/test_handle.py:235]: This should be a `TestFactory` or something similar. `dut` can be accessed via `cocotb.top` from the module scope now.

File: tests/test_cases/test_cocotb/test_handle.py [hunk 9]
```diff
@@ -66,21 +67,193 @@ async def test_delayed_assignment_still_errors(dut):
...
+    """Test integer overflow."""
+    value = gen_int_ovfl_value(32, limits=_Limits.SIGNED_NBIT)
+    await int_overflow_test(dut.stream_in_int, value)
+
+
+@cocotb.test(expect_error=AttributeError if cocotb.SIM_NAME in ["Icarus Verilog"] else ())
+async def test_integer_underflow(dut):
+    """Test integer underflow."""
+    value = gen_int_unfl_value(32, limits=_Limits.SIGNED_NBIT)
+    await int_overflow_test(dut.stream_in_int, value)
```
Comment (ktbarrett) [inline tests/test_cases/test_cocotb/test_handle.py:256]: This could be a `TestFactory` as well, but I think it doesn't handle passing arguments to `cocotb.test`. So nvm, just complaining =)

File: tests/test_cases/test_multi_dimension_array/test_cocotb_array.py (hunk 7 above)
Comment (elgorwi) [reply tests/test_cases/test_multi_dimension_array/test_cocotb_array.py:120]: Fix failing regression test

**Comment by elgorwi** [comment]
> 
> 
> Raising `OverflowError` instead of truncating is a change in behavior, but I don't much care. I'd like to see this change in 1.5. Sorry @elgorwi about dropping the ball on the other PRs.

Comments have been addressed. 
This has all been dragging on for way too long and I can't justify investing any more time on this,

**Review by cmarqu — APPROVED** [review]
Just some minor things; thanks for the contribution!

File: documentation/source/newsfragments/913.change.rst [hunk 10]
```diff
@@ -0,0 +1 @@
+Assigning out-of-range Python ints to signals would truncate the value silently for signal widths <= 32-bit and truncate the value with a warning for signal widths > 32-bit. Assigning out-of-range Python ints to signals will now raise an OverflowError.
```
[the remark this answers is not in the document]
Comment (ktbarrett) [reply documentation/source/newsfragments/913.change.rst:1]: I would add 'previously' after the 'would' in the first sentence for clarity.

**Comment by elgorwi** [comment]
> 
> 
> Just some minor things; thanks for the contribution!

All done

**Review by ktbarrett — APPROVED** [review]

**Comment by ktbarrett** [comment]
Thanks for your effort @elgorwi!
