### PR TITLE
VHPI: Improve get_root_handle()

### LINKED ISSUE #3769: Errors in Xcelium VHDL when architecture & entity have the same name
When attempting to run a VHDL top level in Xcelium, I have a design where the top level entity name is the same as the top level architecture name, which should be valid VHDL. In this scenario, the test fails with an error: `VHPI: Not able to map type (vhpiArchBodyK) 1007 to object`.

I was able to reproduce it on a smaller design by modifying `examples/simple_dff/dff.vhdl` so the architecture is named `dff`, same as the entity. i.e.:
```
entity dff is
...
end dff;

architecture dff of dff is
begin
...
end dff;
```

cocotb version: Installed from master, commit `98c31e425cd7a275a992bad69e84827eb4a6b4b8`
OS Version: Fedora 38, x86_64
Simulator Version: Xcelium 23.09-s005, 64-bit
Python version: 3.11.8, system version

The Xcelium version I'm using should be new enough to have all the required fixes for VHDL, and since I'm installing from master I also have picked up all the relevant fixes on the cocotb side.

I started a thread at https://matrix.to/#/!eqvfxHYGQmlSXRFWJt:gitter.im/$rh8fDZAZSpgF_Xd3ZBNIrMlHmMnooCiuE9VyXtA4k_8?via=gitter.im, and there have been some ideas proposed. I'm opening this issue to collect information towards an official fix.

Here's the full log of the fail
```
$ make SIM=xcelium TOPLEVEL_LANG=vhdl COCOTB_LOG_LEVEL=DEBUG
rm -f results.xml
"make" -f Makefile results.xml
make[1]: Entering directory '/home/rpking42/proj/chips/cocotb/examples/simple_dff'
rm -f results.xml
# Make sure all libs in SOURCES_VHDL_* are mentioned in VHDL_LIB_ORDER and vice versa
set -o pipefail; \
MODULE=test_dff TESTCASE= TOPLEVEL=dff GPI_EXTRA=/home/rpking42/proj/chips/cocotb/venv/lib/python3.11/site-packages/cocotb/libs/libcocotbvhpi_ius.so:cocotbvhpi_entry_point TOPLEVEL_LANG=vhdl \
 /opt/xsite/cte2/tools/cds/Xcelium/23.09/x86/tools/bin/xrun -timescale 1ns/1ps \
-vhdl_time_precision "1ps" \
  -licqueue -64 -xmlibdirpath sim_build -plinowarn -top dff -NEW_VHPI_PROPAGATE_DELAY -loadvpi /home/rpking42/proj/chips/cocotb/venv/lib/python3.11/site-packages/cocotb/libs/libcocotbvpi_ius.so:vlog_startup_routines_bootstrap  -access +rwc -createdebugdb  -makelib dff /home/rpking42/proj/chips/cocotb/examples/simple_dff/dff.vhdl -endlib  2>&1 | tee sim_build/sim.log
TOOL:	xrun(64)	23.09-s005: Started on Mar 05, 2024 at 14:05:34 EST
xrun(64): 23.09-s005: (c) Copyright 1995-2024 Cadence Design Systems, Inc.
Recompiling... reason: file './dff.vhdl' is newer than expected.
	expected: Tue Mar  5 13:56:50 2024
	actual:   Tue Mar  5 14:05:25 2024
     -.--ns INFO     gpi                                ..mbed/gpi_embed.cpp:108  in set_program_name_in_venv        Using Python virtual environment interpreter at /home/rpking42/proj/chips/cocotb/venv/bin/python
     -.--ns INFO     gpi                                ../gpi/GpiCommon.cpp:101  in gpi_print_registered_impl       VPI registered
     -.--ns INFO     gpi                                ../gpi/GpiCommon.cpp:101  in gpi_print_registered_impl       VHPI registered
xmelab: *W,ARCMRA: Elaborating the DFF.DFF:DFF, MRA (most recently analyzed) architecture.
	Elaborating the design hierarchy:
	Top level design units:
		:dff(dff):
	Building instance specific data structures.
	Generating Debug Data:
		LWD Database path: (/home/rpking42/proj/chips/cocotb/examples/simple_dff/sim_build/xcelium.d/dff/dff/dff/debug_db/dff)
		Power Aware Instances:                    0
		Liberty Instances:                        0
		Out Of Module References:                 0
		Assertions:                               0
		Liberty Information:
			PG Pins:	                  0
			Liberty Pins:	                  0
	Design hierarchy summary:
		     Instances  Unique
		Components:  2       1
		Processes:   1       1
	Writing initial simulation snapshot: DFF.DFF:DFF
Loading snapshot dff.dff:dff .................... Done
     -.--ns INFO     gpi                                ..mbed/gpi_embed.cpp:108  in set_program_name_in_venv        Using Python virtual environment interpreter at /home/rpking42/proj/chips/cocotb/venv/bin/python
     -.--ns INFO     gpi                                ../gpi/GpiCommon.cpp:101  in gpi_print_registered_impl       VPI registered
     -.--ns INFO     gpi                                ../gpi/GpiCommon.cpp:101  in gpi_print_registered_impl       VHPI registered
xcelium> run
     0.00ns INFO     cocotb                             Running on xmsim(64) version 23.09-s005
     0.00ns INFO     cocotb                             Running tests with cocotb v2.0.0.dev0+393b3284 from /home/rpking42/proj/chips/cocotb/venv/lib64/python3.11/site-packages/cocotb
     0.00ns DEBUG    gpi                                Looking for packages over 2 implementations
     0.00ns WARNING  gpi                                vpi_iterate returned NULL for type vpiInstance for object NULL
     0.00ns DEBUG    gpi                                Reached end of iterator
     0.00ns INFO     cocotb                             Seeding Python random module with 1709665553
     0.00ns DEBUG    gpi                                Looking for root handle 'dff' over 2 implementations
     0.00ns INFO     gpi                                Nothing visible via VPI
     0.00ns DEBUG    gpi                                VHPI: We have found root=':'
     0.00ns ERROR    gpi                                VHPI: Not able to map type (vhpiArchBodyK) 1007 to object
     0.00ns ERROR    gpi                                No root handle found
     0.00ns ERROR    cocotb                             cocotb testbench initialization failed. Exiting.
                                                        Traceback (most recent call last):
                                                          File "/home/rpking42/proj/chips/cocotb/venv/lib64/python3.11/site-packages/cocotb/__init__.py", line 208, in _initialise_testbench
                                                            _initialise_testbench_(argv_)
                                                          File "/home/rpking42/proj/chips/cocotb/venv/lib64/python3.11/site-packages/cocotb/__init__.py", line 285, in _initialise_testbench_
                                                            raise RuntimeError(f"Can not find root handle ({root_name})")
                                                        RuntimeError: Can not find root handle (dff)
Simulation complete via $finish(1) at time 0 FS + 1
xcelium> exit
TOOL:	xrun(64)	23.09-s005: Exiting on Mar 05, 2024 at 14:05:53 EST  (total: 00:00:19)
ERROR: results.xml was not written by the simulation!
make[1]: *** [/home/rpking42/proj/chips/cocotb/venv/lib/python3.11/site-packages/cocotb/share/makefiles/simulators/Makefile.xcelium:123: results.xml] Error 1
make[1]: Leaving directory '/home/rpking42/proj/chips/cocotb/examples/simple_dff'
make: *** [/home/rpking42/proj/chips/cocotb/venv/lib/python3.11/site-packages/cocotb/share/makefiles/Makefile.inc:40: sim] Error 2
```

### PR DESCRIPTION
**Pull request by marlonjames**
Closes #3769. 

~This removes handle lookup by name~, and instead relies only on `vhpiRootInst`.
When a name is passed in, it is used as a check, which matches VPI and FLI implementations.

I suppose I should add a test for mismatched `TOPLEVEL` envar.

If #3770 comes in first we will have to change the expected failure for Xcelium.

### CODE REVIEW

**Comment by ktbarrett** [comment]
A rebase and updating the expected fail and I'm good. I don't think this needs a newsfrag, but I'll let someone else opine.

**Comment by marlonjames** [comment]
Looks like there is still an issue with Riviera. It is returning `:` for the name of the entity used for the root instantiation.
```
# COUT:      0.00ns WARNING  gpi                                VHPI: DUT ':' doesn't match requested toplevel 'sample_module'
# COUT:      0.00ns ERROR    gpi                                No root handle found
```

**Comment by marlonjames** [comment]
Adding the fallbacks back in, in a different order this time.

File: src/cocotb/share/lib/vhpi/VhpiImpl.cpp [hunk 1]
```diff
@@ -867,72 +867,105 @@ GpiObjHdl *VhpiImpl::native_check_create(int32_t index, GpiObjHdl *parent) {
 
 GpiObjHdl *VhpiImpl::get_root_handle(const char *name) {
     vhpiHandleT root = NULL;
+    std::string root_name;
+
```
Comment (ktbarrett) [inline src/cocotb/share/lib/vhpi/VhpiImpl.cpp:871]: I know the existing style is to declare everything at the top here, but let's make a change. This style is like 30 years antiquated.

File: src/cocotb/share/lib/vhpi/VhpiImpl.cpp [hunk 2]
```diff
@@ -867,72 +867,105 @@ GpiObjHdl *VhpiImpl::native_check_create(int32_t index, GpiObjHdl *parent) {
...
     } else {
-        found = vhpi_get_str(vhpiCaseNameP, dut);
+        return create_gpi_obj_from_handle(root, root_name, root_name);
     }
 
-    if (!dut) {
-        LOG_ERROR("VHPI: Attempting to get the DUT handle failed");
-        return NULL;
-    }
+entity_err:
```
Comment (ktbarrett) [inline src/cocotb/share/lib/vhpi/VhpiImpl.cpp:934]: Instead of `goto` can we use lambdas?

Comment (ktbarrett) [reply src/cocotb/share/lib/vhpi/VhpiImpl.cpp:934]: `return entity_err()`

File: src/cocotb/share/lib/vhpi/VhpiImpl.cpp [hunk 3]
```diff
@@ -866,73 +867,95 @@ GpiObjHdl *VhpiImpl::native_check_create(int32_t index, GpiObjHdl *parent) {
...
+        root_name = vhpi_get_str(vhpiCaseNameP, entity);
 
-    } else {
-        found = vhpi_get_str(vhpiCaseNameP, dut);
+        // If this matches the name then it is what we want,
+        // but we use the root handle two levels up as the DUT
+        // because we do not want an object of type vhpiEntityDeclK as the DUT
+        if (name && !compare_names(name, root_name)) {
+            LOG_DEBUG(
+                "VHPI: entity name '%s' doesn't match requested name '%s'",
```
Comment (ktbarrett) [inline src/cocotb/share/lib/vhpi/VhpiImpl.cpp:919]: Do you want the `Trying fallbacks...` comment here as well?

File: src/cocotb/share/lib/vhpi/VhpiImpl.cpp [hunk 4]
```diff
@@ -866,73 +867,95 @@ GpiObjHdl *VhpiImpl::native_check_create(int32_t index, GpiObjHdl *parent) {
...
+            return create_gpi_obj_from_handle(root, root_name, root_name);
+        }
     }
 
-    if (!dut) {
-        LOG_ERROR("VHPI: Attempting to get the DUT handle failed");
-        return NULL;
-    }
+    // Second, we search for the root handle by name
+    assert(name);
```
Comment (ktbarrett) [inline src/cocotb/share/lib/vhpi/VhpiImpl.cpp:927]:
```suggestion
    if (!name) {
        LOG_ERROR("Couldn't find root handle.");
        return NULL;
    }
```

File: src/cocotb/share/lib/vhpi/VhpiImpl.cpp [hunk 5]
```diff
@@ -866,73 +867,103 @@ GpiObjHdl *VhpiImpl::native_check_create(int32_t index, GpiObjHdl *parent) {
...
+        } else {
+            return create_gpi_obj_from_handle(root, root_name, root_name);
+        }
     }
 
-    if (!found) {
-        LOG_ERROR("VHPI: Unable to query name for DUT handle");
+    // Second, we search for the root handle by name
+    if (!name) {
+        // name should never by null here, but fail if it is.
```
Comment (ktbarrett) [inline src/cocotb/share/lib/vhpi/VhpiImpl.cpp:932]: Should never be null here? Isn't this a fallback path if the above searching fails? Is it not possible that the above could fail and the user didn't pass a name? Maybe I'm missing something.

File: src/cocotb/share/lib/vhpi/VhpiImpl.cpp [hunk 6]
```diff
@@ -27,6 +27,7 @@
 
 #include "VhpiImpl.h"
 
+#include <assert.h>
```
Comment (ktbarrett) [inline src/cocotb/share/lib/vhpi/VhpiImpl.cpp:30]:
```suggestion
```

**Review by ktbarrett — APPROVED** [review]

File: src/cocotb/share/lib/vhpi/VhpiImpl.cpp (hunk 6 above)
Comment (marlonjames) [reply src/cocotb/share/lib/vhpi/VhpiImpl.cpp:30]: Whoops

File: src/cocotb/share/lib/vhpi/VhpiImpl.cpp (hunk 5 above)
Comment (marlonjames) [reply src/cocotb/share/lib/vhpi/VhpiImpl.cpp:932]: If name is null, we'll return the `vhpiRootInst` handle. If we don't get that handle we return a NULL handle without doing the handle lookup by name. That was the previous behavior as well.

So the only way to get here is if a name is passed in for the check, but fails the initial check and the first fallback fails in one of the three ways it could fail.

Comment (cmarqu) [inline src/cocotb/share/lib/vhpi/VhpiImpl.cpp:932]:
```suggestion
        // name should never be null here, but fail if it is.
```

**Comment by cmarqu** [comment]
This is worthy of a newsfragment.

**Review by cmarqu — APPROVED** [review]
